import { Certificate } from "@/app/types/certificate";
import type { Department } from "@/app/types/department";
import { OjtRecord } from "@/app/types/record";
import { Course } from "@/app/types/trainingPlan";
import { User } from "@/app/types/userManagement";

export const departments: Department[] = [
  {
    id: "dept-hr",
    name: "Human Resources",
    division: "Corporate Services",

    manager: {
      id: 1,
      employeeID: "EMP001",
      name: "Sarah Johnson",
      email: "sarah.johnson@company.com",
      phone: "+66 911111111",
      departmentId: 1,
      department: "Human Resources",
      role: "manager",
      status: "active",
      position: "HR Manager",
    },

    totalStaff: 3,

    staff: [
      {
        id: 1,
        employeeID: "ADMIN001",
        name: "System Admin",
        email: "admin@company.com",
        phone: "+66 912345678",
        departmentId: 1,
        department: "Human Resources",
        role: "admin",
        status: "active",
        position: "HR Administrator",
      },
      {
        id: 2,
        employeeID: "EMP002",
        name: "John Carter",
        email: "john.carter@company.com",
        phone: "+66 987654321",
        departmentId: 1,
        department: "Human Resources",
        role: "staff",
        status: "active",
        position: "HR Officer",
      },
      {
        id: 3,
        employeeID: "EMP003",
        name: "Emily Davis",
        email: "emily.davis@company.com",
        phone: "+66 955555555",
        departmentId: 1,
        department: "Human Resources",
        role: "staff",
        status: "active",
        position: "Recruitment Specialist",
      },
    ],
  },

  {
    id: "dept-it",
    name: "Information Technology",
    division: "Technology Services",

    manager: {
      id: 4,
      employeeID: "EMP004",
      name: "Michael Chen",
      email: "michael.chen@company.com",
      phone: "+66 966666666",
      departmentId: 2,
      department: "Information Technology",
      role: "manager",
      status: "active",
      position: "IT Manager",
    },

    totalStaff: 3,

    staff: [
      {
        id: 5,
        employeeID: "EMP005",
        name: "Alice Brown",
        email: "alice.brown@company.com",
        phone: "+66 977777777",
        departmentId: 2,
        department: "Information Technology",
        role: "staff",
        status: "active",
        position: "Frontend Developer",
      },
      {
        id: 6,
        employeeID: "EMP006",
        name: "James Miller",
        email: "james.miller@company.com",
        phone: "+66 988888888",
        departmentId: 2,
        department: "Information Technology",
        role: "staff",
        status: "active",
        position: "DevOps Engineer",
      },
      {
        id: 7,
        employeeID: "EMP007",
        name: "Linda Wong",
        email: "linda.wong@company.com",
        phone: "+66 999999999",
        departmentId: 2,
        department: "Information Technology",
        role: "staff",
        status: "inactive",
        position: "QA Engineer",
      },
    ],
  },
];

export const users: User[] = [
  {
    id: "EMP001",
    name: "John Smith",
    email: "john.smith@company.com",
    phone: "+1 234-567-8901",
    department: {
      id: "DPT001",
      name: "IT",
      manager: { id: 111, name: "Michael Chen", position: "IT Manager" },
      staff: [],
      division: "Technology Services",
    },
    departmentId: "DPT001",
    role: "Developer",
    position: "Senior Developer",
    agency: "HQ",
    cotton: "A",
    line: "1",
    status: "active",
  },
  {
    id: "EMP002",
    name: "Sarah Johnson",
    email: "sarah.j@company.com",
    phone: "+1 234-567-8902",
    department: {
      id: "DPT002",
      name: "HR",
      manager: { id: "EMP002", name: "Sarah Johnson", position: "HR Manager" },
      staff: [],
      division: "Corporate Services",
    },
    departmentId: "DPT002",
    role: "Manager",
    position: "HR Manager",
    agency: "HQ",
    cotton: "A",
    line: "2",
    status: "inactive",
  },
  {
    id: "EMP003",
    name: "Michael Chen",
    email: "michael.c@company.com",
    phone: "+1 234-567-8903",
    department: {
      id: "DPT001",
      name: "IT",
      manager: { id: "EMP003", name: "Michael Chen", position: "IT Manager" },
      staff: [],
      division: "Technology Services",
    },
    departmentId: "DPT001",
    role: "Manager",
    position: "IT Manager",
    agency: "HQ",
    cotton: "B",
    line: "3",
    status: "suspended",
  },
  {
    id: "EMP004",
    name: "Emily Davis",
    email: "emily.d@company.com",
    phone: "+1 234-567-8904",
    department: {
      id: "DPT003",
      name: "Sales",
      manager: { id: "EMP004", name: "Emily Davis", position: "Sales Manager" },
      staff: [],
      division: "Corporate Services",
    },
    departmentId: "DPT003",
    role: "Manager",
    position: "Sales Manager",
    agency: "Branch A",
    cotton: "C",
    line: "4",
    status: "active",
  },
  {
    id: "EMP005",
    name: "Robert Wilson",
    email: "robert.w@company.com",
    phone: "+1 234-567-8905",
    department: {
      id: "DPT004",
      name: "Operations",
      manager: {
        id: "EMP005",
        name: "Robert Wilson",
        position: "Operations Manager",
      },
      staff: [],
      division: "Corporate Services",
    },
    departmentId: "DPT004",
    role: "Manager",
    position: "Operations Manager",
    agency: "Branch B",
    cotton: "D",
    line: "5",
    status: "active",
  },
  {
    id: "EMP006",
    name: "Lisa Anderson",
    email: "lisa.a@company.com",
    phone: "+1 234-567-8906",
    department: {
      id: "DPT005",
      name: "Finance",
      manager: {
        id: "EMP006",
        name: "Lisa Anderson",
        position: "Finance Manager",
      },
      staff: [],
      division: "Corporate Services",
    },
    departmentId: "DPT005",
    role: "Manager",
    position: "Finance Manager",
    agency: "HQ",
    cotton: "A",
    line: "6",
    status: "inactive",
  },
  {
    id: "EMP007",
    name: "Alice Brown",
    email: "alice.b@company.com",
    phone: "+1 234-567-8907",
    department: {
      id: "DPT001",
      name: "IT",
      manager: { id: "EMP003", name: "Michael Chen", position: "IT Manager" },
      staff: [],
      division: "Technology Services",
    },
    departmentId: "DPT001",
    role: "Developer",
    position: "Junior Developer",
    agency: "HQ",
    cotton: "A",
    line: "1",
    status: "active",
  },
  {
    id: "EMP008",
    name: "Bob Wilson",
    email: "bob.w@company.com",
    phone: "+1 234-567-8908",
    department: {
      id: "DPT001",
      name: "IT",
      manager: { id: "EMP003", name: "Michael Chen", position: "IT Manager" },
      staff: [],
      division: "Technology Services",
    },
    departmentId: "DPT001",
    role: "QA Engineer",
    position: "QA Engineer",
    agency: "HQ",
    cotton: "B",
    line: "2",
    status: "suspended",
  },
  {
    id: "EMP009",
    name: "Carol Davis",
    email: "carol.d@company.com",
    phone: "+1 234-567-8909",
    department: {
      id: "DPT001",
      name: "IT",
      manager: { id: "EMP003", name: "Michael Chen", position: "IT Manager" },
      staff: [],
      division: "Technology Services",
    },
    departmentId: "DPT001",
    role: "Designer",
    position: "UI/UX Designer",
    agency: "HQ",
    cotton: "A",
    line: "3",
    status: "active",
  },
  {
    id: "EMP010",
    name: "Tom Harris",
    email: "tom.h@company.com",
    phone: "+1 234-567-8910",
    department: {
      id: "DPT002",
      name: "HR",
      manager: { id: "EMP002", name: "Sarah Johnson", position: "HR Manager" },
      staff: [],
      division: "Corporate Services",
    },
    departmentId: "DPT002",
    role: "HR Specialist",
    position: "HR Specialist",
    agency: "Branch A",
    cotton: "C",
    line: "4",
    status: "active",
  },
];

export const courses: Course[] = [
  {
    id: 1,
    name: "Cybersecurity Best Practices",
    calendarEventId: "cal_001",
    speakerInstitute: "Dr. James Wilson",
    type: "Online",
    category: "Technical Skills",
    date: "2025-11-20",
    numberOfDays: 1,
    numberOfHours: 8,
    location: "Online",
    numberOfPerson: 8,
    costPerPerson: 150,
    totalCost: 1200,
    budgetCode: "IT-SEC-2025",
    content: "An in-depth course on cybersecurity principles and practices.",
  },
  {
    id: 2,
    name: "Leadership Excellence",
    calendarEventId: "cal_002",
    speakerInstitute: "Sarah Martinez",
    type: "Onsite",
    category: "Leadership",
    date: "2025-11-22T",
    numberOfDays: 2,
    numberOfHours: 12,
    location: "Bangkok Office",
    numberOfPerson: 20,
    costPerPerson: 200,
    totalCost: 4000,
    budgetCode: "HR-LDR-2025",
  },
  {
    id: 3,
    name: "Workplace Safety Protocols",
    calendarEventId: "cal_003",
    speakerInstitute: "Michael Brown",
    type: "Onsite",
    category: "Safety",
    date: "2025-11-25",
    numberOfDays: 1,
    numberOfHours: 6,
    location: "Chiang Mai Branch",
    numberOfPerson: 15,
    costPerPerson: 80,
    totalCost: 1200,
    budgetCode: "OPS-SAFE-2025",
  },
  {
    id: 4,
    name: "Data Privacy Compliance",
    calendarEventId: "cal_004",
    speakerInstitute: "Lisa Chen",
    type: "Online",
    category: "Compliance",
    date: "2025-11-28",
    numberOfDays: 1,
    numberOfHours: 10,
    location: "Online",
    numberOfPerson: 12,
    costPerPerson: 120,
    totalCost: 1440,
    budgetCode: "LEGAL-DATA-2025",
  },
];

export const TrainingTypeEnum = ["In-house", "Public", "OJT", "Self-learning", "Online/Virtual"] as const;

export const TrainingCategoryEnum = [
  "สนับสนุนนโยบายสิ่งแวดล้อม",
        "ความปลอดภัยและอาชีวอนามัย",
        "งานขายและงานบริการ",
        "การใช้งาน Software",
        "การนำเสนอ",
        "Leadership Development",
        "การใช้งานเครื่องจักรและซ่อมบำรุง",
        "กระบวนการคิด วิเคราะห์",
        "พัฒนาทักษะกระบวนการทำงาน",
        "การจัดซื้อจัดจ้าง",
        "การสื่อสาร",
        "โครงการสัมมนาอื่นๆ",
        "พัฒนาขีดความสามารถระดับบริหาร",
        "การเงินและการบัญชี"
] as const;

export const certificates: Certificate[] = [
  {
    id: 7,
    userId: 2,
    userName: "Aung Min Oo",
    employeeId: "EMP002",
    department: "IT",
    division: "Division B",
    category: "การใช้งาน Software",
    trainingId: 1,
    trainingName: "Advanced Go Backend Development",
    image: "certificates/user_2/1770907868.jpeg",
    description: "I want to get a high salary. I like it very much.",
    status: "Pending",
    createdAt: "2026-02-12T21:51:08.317+07:00",
    updatedAt: "2026-02-12T21:51:08.317+07:00",
  },
  {
    id: 8,
    userId: 3,
    userName: "Chan Nyein Thu",
    employeeId: "EMP003",
    department: "HR",
    division: "Division A",
    category: "Leadership Development",
    trainingId: 2,
    trainingName: "Strategic HR Management",
    image: "certificates/user_3/1770908000.jpeg",
    description: "Improve leadership and communication skills.",
    status: "Approved",
    createdAt: "2026-02-13T09:20:10.100+07:00",
    updatedAt: "2026-02-13T10:00:00.000+07:00",
  },
  {
    id: 9,
    userId: 4,
    userName: "Sarah Johnson",
    employeeId: "EMP004",
    department: "Finance",
    division: "Division C",
    category: "การเงินและการบัญชี",
    trainingId: 3,
    trainingName: "Financial Analysis Advanced",
    image: "certificates/user_4/1770908200.jpeg",
    description: "Enhance financial reporting skills.",
    status: "Rejected",
    createdAt: "2026-02-14T14:15:30.000+07:00",
    updatedAt: "2026-02-14T16:30:00.000+07:00",
  },
];

export const ojtRecords: OjtRecord[] = [
  {
    id: 1,
    staff: users[0],
    course: courses[0],
    status: "COMPLETED",
  },
  {
    id: 2,
    staff: users[1],
    course: courses[0],
    status: "IN_PROGRESS",
  },
  {
    id: 3,
    staff: users[2],
    course: courses[0],
    status: "NOT_STARTED",
  },
];
